# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Georgie99/6bc88268dc959002510d884f40d897c3/untitled4.ipynb
"""

import requests
import json
import prettytable
headers = {'Content-type': 'application/json'}
data = json.dumps({"seriesid": ['JTS00000000JOR',''],"startyear":"2010", "endyear":"2020"})
                  # ['CUUR0000SA0','SUUR0000SA0'],"startyear":"2011", "endyear":"2014"})
p = requests.post('https://api.bls.gov/publicAPI/v2/timeseries/data/', data=data, headers=headers)
json_data = json.loads(p.text)
for series in json_data['Results']['series']:
    x=prettytable.PrettyTable(["series id","year","period","value","footnotes"])
    seriesId = series['seriesID']
    for item in series['data']:
        year = item['year']
        period = item['period']
        value = item['value']
        footnotes=""
        for footnote in item['footnotes']:
            if footnote:
                footnotes = footnotes + footnote['text'] + ','
        if 'M01' <= period <= 'M12':
            x.add_row([seriesId,year,period,value,footnotes[0:-1]])
    output = open(seriesId + '.txt','w')
    output.write (x.get_string())
    output.close()

import requests
url = 'https://api.bls.gov/publicAPI/v1/timeseries/data/JTS00000000JOR' # using the Inflation & Prices average price series
data = requests.get(url).json()
print('Status: ' + data['status'])
print((data))
data["Results"]["series"][0]

import json
import pandas as pd
##data = json.load(open('data.json'))
##df = pd.DataFrame(data["result"])
df = pd.DataFrame(data["Results"]["series"][0])
df

from google.colab import files
uploaded = files.upload()

import pandas as pd
import io

df = pd.read_csv(io.StringIO(uploaded['job openings.csv'].decode('utf-8')))
df

import plotly
plotly.__version__
!pip install chart-studio

import chart_studio.plotly as py
import plotly.graph_objs as go
import plotly.figure_factory as FF

import numpy as np
import pandas as pd

df1 = pd.read_csv('job openings.csv')

sample_data_table = FF.create_table(df1.head())
py.iplot(sample_data_table, filename='sample-data-table')

trace1 = go.Scatter(
                    x=df1['x'], y=df1['logx'], # Data
                    mode='lines', name='logx' # Additional options
                   )
trace2 = go.Scatter(x=df1['x'], y=df1['sinx'], mode='lines', name='sinx' )
trace3 = go.Scatter(x=df1['x'], y=df1['cosx'], mode='lines', name='cosx')

layout = go.Layout(title='Simple Plot from csv data',
                   plot_bgcolor='rgb(230, 230,230)')

fig = go.Figure(data=[trace1, trace2, trace3], layout=layout)

# Plot data in the notebook
py.iplot(fig, filename='simple-plot-from-csv')